#Post request to create new patient

POST http://localhost:4000/patients
Content-Type: application/json

{
  "fullName": "anas kafka test 5",
  "email": "anasKafka5@test.com",
  "address": "amman - jordan",
  "barthDate": "2000-09-14"

}
