server:
  port: 4004

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## REST CLIENT --> http://localhost:4004/api/patients
            ## API GATEWAY --> http://patient-service:4000/patients
            ## PATIENT SERVICE (SPRING BOOT APP) --> /patients --> Patient Array
            - id: patient-service-route
              uri: http://patient-service:4000
              predicates:
                - Path=/api/patients/**
              filters:
                - StripPrefix=1